python -m domainbed.scripts.sweep relaunch\
    --data_dir=./data \
    --output_dir=./results/a3w_test/  \
    --command_launcher multi_gpu    \
    --algorithms NLPGERM     \
    --datasets PACS  \
    --skip_confirmation \
    --n_hparams_from 0  \
    --n_hparams 1       \
    --n_trials 1       \
    --holdout_fraction 0.2  \
    --hparams '{"flip_prob":0.25, "study_noise":1, "mapsty":"itera", "lambda":1.0}' \
    --steps 5000      \
    --test_envs 0    \
    --task domain_generalization 